/**
 * Canonical fallback data for RecoverAI.
 * Exactly preserves Seed 42 frozen benchmark metrics.
 */

import { AnalyticsResponse, OverviewData, RecoveryCaseItem, SafeguardsResponse } from "./types";

export const CANONICAL_OVERVIEW: OverviewData = {
  environment: "Simulation / Razorpay Test Mode",
  system_status: "All Safeguards Operational (0 bps Unsafe)",
  kpis: {
    amount_at_risk_minor: 531161966,
    amount_at_risk_display: "₹53,11,619.66",
    authorized_amount_minor: 85259735,
    authorized_amount_display: "₹8,52,597.35",
    recovered_amount_minor: 56195598,
    recovered_amount_display: "₹5,61,955.98",
    deferred_amount_minor: 29064137,
    deferred_amount_display: "₹2,90,641.37",
    blocked_amount_minor: 184300717,
    blocked_amount_display: "₹18,43,007.17",
    review_amount_minor: 261601514,
    review_amount_display: "₹26,16,015.14",
    recovery_rate_bps: 6591,
    recovery_rate_display: "65.9%",
    total_cases_count: 1676,
    authorized_cases_count: 689,
    blocked_cases_count: 719,
    review_cases_count: 268,
    attempted_cases_count: 456,
    recovered_cases_count: 456,
    deferred_cases_count: 233,
  },
  funnel: [
    { stage: "Failed Payments", count: 1676, amount_minor: 531161966, percentage: 100 },
    { stage: "Revenue at Risk", count: 1676, amount_minor: 531161966, percentage: 100 },
    { stage: "AI Diagnosed", count: 1676, amount_minor: 531161966, percentage: 100 },
    { stage: "Gateway Authorized", count: 689, amount_minor: 85259735, percentage: 41.1 },
    { stage: "Execution Attempted", count: 456, amount_minor: 56195598, percentage: 27.2 },
    { stage: "Confirmed Recovered", count: 456, amount_minor: 56195598, percentage: 27.2 },
  ],
  safeguards_summary: {
    kill_switch_active: false,
    unauthorized_execution_rate_bps: 0,
    duplicate_execution_rate_bps: 0,
    financial_integrity_violation_rate_bps: 0,
    blocked_cases_count: 719,
    review_cases_count: 268,
  },
};

export const CANONICAL_CASES: RecoveryCaseItem[] = [
  // Demo 1: Recoverable Temporary Failure (Golden Path)
  {
    case_id: "c4a7e912-78d1-4f32-8419-a1d2f9b8c001",
    target_type: "payment",
    target_id: "p1a7e912-78d1-4f32-8419-a1d2f9b8c001",
    customer_id: "u1a7e912-78d1-4f32-8419-a1d2f9b8c001",
    customer_name: "Aditya Sharma",
    customer_email: "aditya.sharma@techcorp.in",
    amount_minor: 150000,
    currency: "INR",
    latest_failure_code: "temporary_failure",
    target_attempt_count: 1,
    customer_success_rate_bps: 9200,
    subscription_status: null,
    risk_level: "MEDIUM",
    risk_score_bps: 8200,
    predicted_recoverable: true,
    ai_diagnosis: {
      root_cause: "Temporary issuing bank 3DS handshake timeout during peak traffic window.",
      recoverability: "RECOVERABLE",
      recoverability_reason: "High historical customer reliability (92%) and non-persisting network failure code.",
      confidence: "HIGH",
      failure_category: "NETWORK_TIMEOUT",
      evidence: [
        { signal_type: "CUSTOMER_HISTORY", description: "12 previous successful transactions over 6 months", relevance: "HIGH" },
        { signal_type: "DECLINE_NATURE", description: "Transient 504 gateway response from issuer switch", relevance: "HIGH" },
        { signal_type: "RETRY_BUDGET", description: "First failure attempt (budget 2 remaining)", relevance: "MEDIUM" },
      ],
      observed_facts: ["Amount: ₹1,500.00", "Attempt count: 1", "Decline: temporary_failure"],
      model: "MockLLM-v1",
      prompt_version: "v1",
    },
    decision_proposal: {
      proposal_id: "d4a7e912-78d1-4f32-8419-a1d2f9b8c001",
      action_type: "RETRY_PAYMENT",
      decision_status: "PROPOSED",
      rationale: "Temporary network failure with excellent customer repayment history warrants immediate smart automated retry.",
      observed_facts: ["Reliable transaction history", "Single failure instance"],
      ai_inferences: ["Transient network glitch rather than insolvency"],
      policy_checks: ["Attempts <= 2 (PASS)", "Amount < ₹5,000 (PASS)"],
    },
    gateway_result: {
      gateway_decision: "APPROVED",
      reason_code: "APPROVED_FOR_EXECUTION_LAYER",
      eligible_for_execution_layer: true,
      checks_evaluated: [
        "check_kill_switch",
        "check_schema_and_version",
        "check_proposal_identity",
        "check_financial_integrity",
        "check_idempotency",
        "check_action_allowlist",
        "check_retry_ceiling",
        "check_chronic_declines",
        "check_high_value",
        "check_rate_limit",
      ],
      checks_passed: [
        "check_kill_switch",
        "check_schema_and_version",
        "check_proposal_identity",
        "check_financial_integrity",
        "check_idempotency",
        "check_action_allowlist",
        "check_retry_ceiling",
        "check_chronic_declines",
        "check_high_value",
        "check_rate_limit",
      ],
      blocking_conditions: [],
      audit_reference: "audit-001-a1d2f9b8c001",
    },
    execution_record: {
      execution_id: "e4a7e912-78d1-4f32-8419-a1d2f9b8c001",
      status: "SUCCEEDED",
      attempt_number: 2,
      provider_reference: "pay_test_99a81b2c4d",
      idempotency_key: "rec-exec-d4a7e912-78d1-4f32-8419-a1d2f9b8c001",
      amount_minor: 150000,
      created_at: "2026-09-03T09:41:04Z",
    },
    timeline: [
      { stage: "PAYMENT_FAILED", timestamp: "09:41:01", title: "Payment Failed", description: "Declined: temporary_failure", status: "FAILED" },
      { stage: "RISK_DETECTED", timestamp: "09:41:02", title: "Risk Evaluated", description: "₹1,500 at risk, 92% customer success rate", status: "COMPLETED" },
      { stage: "AI_DIAGNOSIS", timestamp: "09:41:03", title: "AI Root-Cause Diagnosis", description: "Network timeout during 3DS verification", status: "COMPLETED" },
      { stage: "RECOVERY_DECISION", timestamp: "09:41:03", title: "Proposal Synthesized", description: "Action: RETRY_PAYMENT", status: "COMPLETED" },
      { stage: "SAFETY_GATEWAY", timestamp: "09:41:04", title: "Gateway Authorization", description: "APPROVED: 10 safety invariants passed", status: "PASSED" },
      { stage: "EXECUTION", timestamp: "09:41:04", title: "Bounded Execution", description: "Dispatched to Razorpay Test Adapter", status: "SUCCEEDED" },
      { stage: "RECONCILED", timestamp: "09:41:05", title: "Revenue Reconciled", description: "Confirmed ₹1,500.00 recovered", status: "RECONCILED" },
    ],
  },

  // Demo 2: Insufficient Funds (Cooldown Coordinated Retry)
  {
    case_id: "c4a7e912-78d1-4f32-8419-a1d2f9b8c002",
    target_type: "payment",
    target_id: "p1a7e912-78d1-4f32-8419-a1d2f9b8c002",
    customer_id: "u1a7e912-78d1-4f32-8419-a1d2f9b8c002",
    customer_name: "Priya Nair",
    customer_email: "priya.nair@enterprises.org",
    amount_minor: 320000,
    currency: "INR",
    latest_failure_code: "insufficient_funds",
    target_attempt_count: 1,
    customer_success_rate_bps: 8800,
    subscription_status: null,
    risk_level: "MEDIUM",
    risk_score_bps: 7800,
    predicted_recoverable: true,
    ai_diagnosis: {
      root_cause: "Temporary account balance deficit near month-end payroll cycle.",
      recoverability: "RECOVERABLE",
      recoverability_reason: "Customer has recurring salary cadence; delayed retry aligns with replenishment.",
      confidence: "HIGH",
      failure_category: "INSUFFICIENT_FUNDS",
      evidence: [
        { signal_type: "CADENCE", description: "Customer typically settles between 1st-3rd of calendar month", relevance: "HIGH" },
        { signal_type: "RECOVERY_SIGNAL", description: "Past insufficient funds auto-resolved on next business day", relevance: "MEDIUM" },
      ],
      observed_facts: ["Amount: ₹3,200.00", "Decline: insufficient_funds"],
      model: "MockLLM-v1",
      prompt_version: "v1",
    },
    decision_proposal: {
      proposal_id: "d4a7e912-78d1-4f32-8419-a1d2f9b8c002",
      action_type: "RETRY_LATER",
      decision_status: "PROPOSED",
      rationale: "Immediate retry would fail. Policy schedules a 24h cooldown to maximize balance replenishment odds.",
      observed_facts: ["Insufficient funds decline"],
      ai_inferences: ["Likely salary deposit pending"],
      policy_checks: ["Cooldown policy activated", "Attempt budget preserved"],
    },
    gateway_result: {
      gateway_decision: "APPROVED",
      reason_code: "APPROVED_FOR_EXECUTION_LAYER",
      eligible_for_execution_layer: true,
      checks_evaluated: ["check_kill_switch", "check_schema", "check_identity", "check_financial_integrity"],
      checks_passed: ["check_kill_switch", "check_schema", "check_identity", "check_financial_integrity"],
      blocking_conditions: [],
      audit_reference: "audit-002-a1d2f9b8c002",
    },
    execution_record: {
      execution_id: "e4a7e912-78d1-4f32-8419-a1d2f9b8c002",
      status: "DEFERRED",
      attempt_number: 1,
      provider_reference: null,
      idempotency_key: "rec-exec-d4a7e912-78d1-4f32-8419-a1d2f9b8c002",
      amount_minor: 320000,
      created_at: "2026-09-03T09:42:10Z",
    },
    timeline: [
      { stage: "PAYMENT_FAILED", timestamp: "09:42:01", title: "Payment Declined", description: "Code: insufficient_funds", status: "FAILED" },
      { stage: "RISK_DETECTED", timestamp: "09:42:02", title: "Risk Detected", description: "₹3,200 at risk, strong customer tenure", status: "COMPLETED" },
      { stage: "AI_DIAGNOSIS", timestamp: "09:42:03", title: "AI Diagnosis", description: "Temporary balance deficit", status: "COMPLETED" },
      { stage: "RECOVERY_DECISION", timestamp: "09:42:04", title: "Proposal", description: "Action: RETRY_LATER (24h Cooldown)", status: "COMPLETED" },
      { stage: "SAFETY_GATEWAY", timestamp: "09:42:05", title: "Gateway Approval", description: "APPROVED: Deferred action approved", status: "PASSED" },
      { stage: "EXECUTION", timestamp: "09:42:06", title: "Status: DEFERRED", description: "Zero immediate charge; waiting for scheduled window", status: "DEFERRED" },
    ],
  },

  // Demo 3: High-Value Payment (Human Review Mandatory Escalation)
  {
    case_id: "c4a7e912-78d1-4f32-8419-a1d2f9b8c003",
    target_type: "payment",
    target_id: "p1a7e912-78d1-4f32-8419-a1d2f9b8c003",
    customer_id: "u1a7e912-78d1-4f32-8419-a1d2f9b8c003",
    customer_name: "Vikram Malhotra",
    customer_email: "v.malhotra@zenithholdings.com",
    amount_minor: 1250000,
    currency: "INR",
    latest_failure_code: "limit_exceeded",
    target_attempt_count: 1,
    customer_success_rate_bps: 9500,
    subscription_status: null,
    risk_level: "HIGH",
    risk_score_bps: 9400,
    predicted_recoverable: true,
    ai_diagnosis: {
      root_cause: "High-value B2B invoice exceeded daily card limit threshold.",
      recoverability: "RECOVERABLE",
      recoverability_reason: "High enterprise solvency; requires customer account manager authorization or wire option.",
      confidence: "HIGH",
      failure_category: "LIMIT_EXCEEDED",
      evidence: [
        { signal_type: "HIGH_VALUE_THRESHOLD", description: "Amount ₹12,500 exceeds high-value threshold (₹5,000)", relevance: "CRITICAL" },
        { signal_type: "ENTERPRISE_ACCOUNT", description: "Verified corporate billing tier with 95% settlement rate", relevance: "HIGH" },
      ],
      observed_facts: ["Amount: ₹12,500.00", "Threshold: ₹5,000.00 exceeded"],
      model: "MockLLM-v1",
      prompt_version: "v1",
    },
    decision_proposal: {
      proposal_id: "d4a7e912-78d1-4f32-8419-a1d2f9b8c003",
      action_type: "HUMAN_REVIEW",
      decision_status: "ESCALATED",
      rationale: "Amount >= ₹5,000 triggers strict mandatory human review policy invariant. Automated execution prohibited.",
      observed_facts: ["High-value invoice: ₹12,500.00"],
      ai_inferences: ["Requires white-glove manual supervisor token"],
      policy_checks: ["High-Value Escalation Threshold Tripped (PASS-HOLD)"],
    },
    gateway_result: {
      gateway_decision: "REQUIRES_REVIEW",
      reason_code: "HIGH_VALUE_REQUIRES_REVIEW",
      eligible_for_execution_layer: false,
      checks_evaluated: ["check_kill_switch", "check_schema", "check_high_value"],
      checks_passed: ["check_kill_switch", "check_schema"],
      blocking_conditions: ["HIGH_VALUE_EXCEEDS_500000_MINOR_UNITS"],
      audit_reference: "audit-003-a1d2f9b8c003",
    },
    execution_record: null,
    timeline: [
      { stage: "PAYMENT_FAILED", timestamp: "09:43:01", title: "High-Value Transaction Declined", description: "₹12,500.00 declined: limit_exceeded", status: "FAILED" },
      { stage: "RISK_DETECTED", timestamp: "09:43:02", title: "Critical Revenue at Risk", description: "High risk enterprise exposure", status: "COMPLETED" },
      { stage: "AI_DIAGNOSIS", timestamp: "09:43:03", title: "AI Assessment", description: "Enterprise card limit reached", status: "COMPLETED" },
      { stage: "RECOVERY_DECISION", timestamp: "09:43:04", title: "Escalated to Operations", description: "Action: HUMAN_REVIEW", status: "COMPLETED" },
      { stage: "SAFETY_GATEWAY", timestamp: "09:43:05", title: "Gateway: REQUIRES_REVIEW", description: "Automated payment blocked pending supervisor token", status: "REQUIRES_REVIEW" },
    ],
  },

  // Demo 4: Unsafe Repeated Failure (Hard Policy Block)
  {
    case_id: "c4a7e912-78d1-4f32-8419-a1d2f9b8c004",
    target_type: "payment",
    target_id: "p1a7e912-78d1-4f32-8419-a1d2f9b8c004",
    customer_id: "u1a7e912-78d1-4f32-8419-a1d2f9b8c004",
    customer_name: "Rahul Verma",
    customer_email: "r.verma@freemail.com",
    amount_minor: 85000,
    currency: "INR",
    latest_failure_code: "do_not_honor",
    target_attempt_count: 3,
    customer_success_rate_bps: 1800,
    subscription_status: null,
    risk_level: "HIGH",
    risk_score_bps: 1200,
    predicted_recoverable: false,
    ai_diagnosis: {
      root_cause: "Chronic hard card decline with depleted retries and low historical settlement.",
      recoverability: "UNRECOVERABLE",
      recoverability_reason: "Issuer returned hard 'do_not_honor' decline code across 3 separate attempts.",
      confidence: "HIGH",
      failure_category: "HARD_DECLINE",
      evidence: [
        { signal_type: "ATTEMPT_EXHAUSTION", description: "3 attempts recorded (max ceiling is 2)", relevance: "CRITICAL" },
        { signal_type: "CHRONIC_DECLINE", description: "Customer historical success rate is 18% (<25% threshold)", relevance: "CRITICAL" },
      ],
      observed_facts: ["Attempts: 3", "Decline: do_not_honor", "Customer history: 18%"],
      model: "MockLLM-v1",
      prompt_version: "v1",
    },
    decision_proposal: {
      proposal_id: "d4a7e912-78d1-4f32-8419-a1d2f9b8c004",
      action_type: "NO_ACTION",
      decision_status: "BLOCKED",
      rationale: "Attempt limit exhausted and chronic failure invariant breached. Card spamming prohibited.",
      observed_facts: ["3 failed attempts", "Chronic low settlement"],
      ai_inferences: ["Persistent non-recoverable card decline"],
      policy_checks: ["Max Retries Cap Exceeded (HARD BLOCK)", "Chronic Decline Cap (HARD BLOCK)"],
    },
    gateway_result: {
      gateway_decision: "BLOCKED",
      reason_code: "BLOCK_NON_EXECUTABLE_ACTION",
      eligible_for_execution_layer: false,
      checks_evaluated: ["check_kill_switch", "check_schema", "check_retry_ceiling", "check_chronic_declines"],
      checks_passed: ["check_kill_switch", "check_schema"],
      blocking_conditions: ["ATTEMPT_COUNT_GE_3_VIOLATION", "CHRONIC_UNRESOLVED_DECLINE"],
      audit_reference: "audit-004-a1d2f9b8c004",
    },
    execution_record: null,
    timeline: [
      { stage: "PAYMENT_FAILED", timestamp: "09:44:01", title: "Third Payment Attempt Failed", description: "Code: do_not_honor", status: "FAILED" },
      { stage: "RISK_DETECTED", timestamp: "09:44:02", title: "Severe Risk Assessed", description: "Chronic decline history", status: "COMPLETED" },
      { stage: "AI_DIAGNOSIS", timestamp: "09:44:03", title: "AI Analysis", description: "Unrecoverable hard decline", status: "COMPLETED" },
      { stage: "RECOVERY_DECISION", timestamp: "09:44:04", title: "Policy Block Enforced", description: "NO_ACTION: Hard safety block", status: "COMPLETED" },
      { stage: "SAFETY_GATEWAY", timestamp: "09:44:05", title: "Gateway: BLOCKED", description: "Zero execution permitted. Gateway safeguards customer from card spamming.", status: "BLOCKED" },
    ],
  },

  // Demo 5: Subscription Recovery Workflow
  {
    case_id: "c4a7e912-78d1-4f32-8419-a1d2f9b8c005",
    target_type: "subscription",
    target_id: "s1a7e912-78d1-4f32-8419-a1d2f9b8c005",
    customer_id: "u1a7e912-78d1-4f32-8419-a1d2f9b8c005",
    customer_name: "Ananya Desai",
    customer_email: "ananya.d@fintechinnovate.com",
    amount_minor: 120000,
    currency: "INR",
    latest_failure_code: "card_inactive",
    target_attempt_count: 1,
    customer_success_rate_bps: 9100,
    subscription_status: "past_due",
    risk_level: "MEDIUM",
    risk_score_bps: 8100,
    predicted_recoverable: true,
    ai_diagnosis: {
      root_cause: "Mandated recurring auto-debit token expired on SaaS subscription.",
      recoverability: "RECOVERABLE",
      recoverability_reason: "Customer active and utilizing service; subscription workflow initiates e-mandate renewal.",
      confidence: "HIGH",
      failure_category: "SUBSCRIPTION_DUNNING",
      evidence: [
        { signal_type: "SUBSCRIPTION_STATUS", description: "Status: past_due with active usage", relevance: "HIGH" },
        { signal_type: "TOKEN_EXPIRED", description: "RBI e-mandate requires re-authorization", relevance: "HIGH" },
      ],
      observed_facts: ["Subscription past_due", "Amount: ₹1,200.00"],
      model: "MockLLM-v1",
      prompt_version: "v1",
    },
    decision_proposal: {
      proposal_id: "d4a7e912-78d1-4f32-8419-a1d2f9b8c005",
      action_type: "SUBSCRIPTION_RECOVERY_WORKFLOW",
      decision_status: "PROPOSED",
      rationale: "Past due subscription requires automated recurring dunning and re-tokenization sequence.",
      observed_facts: ["Subscription past due", "Auto-debit failure"],
      ai_inferences: ["Customer intends to maintain active subscription"],
      policy_checks: ["Subscription workflow routing active"],
    },
    gateway_result: {
      gateway_decision: "APPROVED",
      reason_code: "APPROVED_FOR_EXECUTION_LAYER",
      eligible_for_execution_layer: true,
      checks_evaluated: ["check_kill_switch", "check_schema", "check_identity", "check_financial_integrity"],
      checks_passed: ["check_kill_switch", "check_schema", "check_identity", "check_financial_integrity"],
      blocking_conditions: [],
      audit_reference: "audit-005-a1d2f9b8c005",
    },
    execution_record: {
      execution_id: "e4a7e912-78d1-4f32-8419-a1d2f9b8c005",
      status: "SUCCEEDED",
      attempt_number: 2,
      provider_reference: "sub_test_4488b1cc99",
      idempotency_key: "rec-exec-d4a7e912-78d1-4f32-8419-a1d2f9b8c005",
      amount_minor: 120000,
      created_at: "2026-09-03T09:45:12Z",
    },
    timeline: [
      { stage: "PAYMENT_FAILED", timestamp: "09:45:01", title: "Subscription Renewal Failed", description: "Recurring token inactive", status: "FAILED" },
      { stage: "RISK_DETECTED", timestamp: "09:45:02", title: "Churn Risk Detected", description: "SaaS MRR at risk", status: "COMPLETED" },
      { stage: "AI_DIAGNOSIS", timestamp: "09:45:03", title: "AI Diagnosis", description: "E-mandate renewal required", status: "COMPLETED" },
      { stage: "RECOVERY_DECISION", timestamp: "09:45:04", title: "Workflow Triggered", description: "SUBSCRIPTION_RECOVERY_WORKFLOW", status: "COMPLETED" },
      { stage: "SAFETY_GATEWAY", timestamp: "09:45:05", title: "Gateway Approval", description: "APPROVED for subscription recovery", status: "PASSED" },
      { stage: "EXECUTION", timestamp: "09:45:06", title: "Execution Succeeded", description: "Recurring mandate regenerated & charged", status: "SUCCEEDED" },
      { stage: "RECONCILED", timestamp: "09:45:07", title: "Subscription Reconciled", description: "Recovered ₹1,200.00", status: "RECONCILED" },
    ],
  },
];

export const CANONICAL_SAFEGUARDS: SafeguardsResponse = {
  kill_switch_active: false,
  payment_mode: "Simulation / Razorpay Test Mode",
  gateway_version: "v1",
  policy_version: "v1",
  decision_version: "v1",
  retry_policy: {
    max_attempts_cap: 2,
    high_value_threshold_minor: 500000,
    high_value_display: "₹5,000.00",
    cooldown_period_seconds: 86400,
  },
  critical_safety_metrics: {
    unauthorized_execution_rate_bps: 0,
    duplicate_execution_rate_bps: 0,
    financial_integrity_violation_rate_bps: 0,
    unsafe_authorization_rate_bps: 0,
  },
  blocked_reasons_distribution: {
    BLOCK_NON_EXECUTABLE_ACTION: 704,
    BLOCK_UNRESOLVED_HARD_DECLINE: 15,
    MISSING_HUMAN_APPROVAL: 268,
  },
};

export const CANONICAL_ANALYTICS: AnalyticsResponse = {
  benchmark_summary: {
    total_evaluated_minor: 531161966,
    total_evaluated_display: "₹53,11,619.66",
    authorized_minor: 85259735,
    authorized_display: "₹8,52,597.35",
    recovered_minor: 56195598,
    recovered_display: "₹5,61,955.98",
    deferred_minor: 29064137,
    deferred_display: "₹2,90,641.37",
    blocked_minor: 184300717,
    blocked_display: "₹18,43,007.17",
    requires_review_minor: 261601514,
    requires_review_display: "₹26,16,015.14",
  },
  conversion_rates: {
    gross_recovery_rate_bps: 1058,
    gross_recovery_display: "10.6%",
    authorized_conversion_rate_bps: 6591,
    authorized_conversion_display: "65.9%",
  },
  action_breakdown: [
    { action: "RETRY_PAYMENT", count: 444, amount_minor: 54695598, status: "EXECUTED" },
    { action: "RETRY_LATER", count: 233, amount_minor: 29064137, status: "DEFERRED" },
    { action: "SUBSCRIPTION_RECOVERY_WORKFLOW", count: 12, amount_minor: 1500000, status: "EXECUTED" },
    { action: "HUMAN_REVIEW", count: 268, amount_minor: 261601514, status: "ESCALATED" },
    { action: "NO_ACTION", count: 719, amount_minor: 184300717, status: "BLOCKED" },
  ],
};
